config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts
  get 'about', to: 'pages#about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 4, maximum: 50 }
  validates :body, presence: true, length: { minimum: 20, maximum: 200 }
  has_one_attached :image
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end

  def about; end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-custom">
  <div class="container-fluid">
    <%= link_to "Job Rocket", root_path, class: "navbar-brand text-bold text-white"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link text-white"%>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link text-white"%>
        </li>
        <li class="nav-item">
          <%= link_to "Jobs", posts_path, class: "nav-link text-white"%>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <button class="btn btn-light dropdown-toggle" type="button" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </button>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job Rocket</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application.tailwind', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <style>
      .bg-custom {
        background-color: #32127a;
      }
      .bg-error {
        background-color: #F5D1D3;
      }
      .text-white {
        color: white !important;
      }
      .text-bold {
        font-weight: bold;
      }
    </style>
  </head>

  <body> 
    <%= render "layouts/navbar" %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<div class="container">

<h1>Homepage</h1>
<p>Read more about me</p>

<%= link_to "About", about_path %>

</div>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true, html: { multipart: true }) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation" class="bg-red-100 text-red-800 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control shadow-sm border border-gray-400 rounded-md mt-2" %>
  </div>

  <div class="my-5">
    <%= form.label :body, class: "form-label" %>
    <%= form.text_area :body, rows: 4, class: "form-control shadow-sm border border-gray-400 rounded-md mt-2" %>
  </div>

  <div class="my-5">
    <%= form.label :image, class: "form-label" %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="inline">
    <%= form.submit class: "btn btn-primary rounded-lg py-3 px-5 font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p class="my-5">
    
    <h2><%= post.title %> </h2>
  </p>

  <div class="my-5">
  
  <h6>  <%= post.body %> </h6>
  </div>
  <% if @post.image.present? %>
  <%= image_tag @post.image.url, size: "600x400", class: "img-fluid" %>
<% end %>
</div>

app/views/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Show this post", @post, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to posts", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/index.html.erb
<!-- app/views/posts/index.html.erb -->
<div class="container mt-5">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-success text-white font-medium rounded-lg" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Posts" %>

  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="font-weight-bold">Jobs</h1>
    <%= link_to "New post", new_post_path, class: "btn btn-dark" %>
  </div>

<div id="posts" class="row">
  <% @posts.each do |post| %>
    <div class="col-md-4 mb-4">
      <div class="bg-purple-600 p-4 rounded-lg shadow-md">
       <% if post.image.attached? %>
          <%= image_tag post.image, class: "img-fluid rounded" %>
        <% end %>
        <h2 class="font-bold text-xl mb-2"><%= post.title %></h2>
        <p class="text-base"><%= post.body %></p>
       
        <%= link_to "Show this post", post, class: "btn btn-light mt-2" %>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/posts/new.html.erb
<!-- app/views/posts/new.html.erb or other relevant view -->
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <h1 class="text-center mb-4">Create New Post</h1>

      <!-- Render the form with Bootstrap styling -->
      <%= render "form", post: @post %>

      <div class="text-center mt-4">
        <%= link_to "Back to posts", posts_path, class: "btn btn-secondary btn-lg" %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex flex-col items-center">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
      <%= notice %>
    </p>
  <% end %>

  <% if @post.image.attached? %>
    <%= image_tag @post.image, class: "w-full max-w-md rounded-lg shadow-md" %>
  <% else %>
    <p>No image available</p>
  <% end %>

  <h1 class="text-2xl font-bold mt-4"><%= @post.title %></h1>
  <p class="text-base mt-2"><%= @post.body %></p>

  <div class="mt-4 flex space-x-2">
    <%= link_to "Edit this post", edit_post_path(@post), class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    <%= link_to "Back to posts", posts_path, class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    <%= button_to "Delete", @post, method: :delete, class: "rounded-lg py-3 px-5 bg-red-600 text-white font-medium", data: { confirm: "Are you sure?" } %>
  </div>
</div>